version: '3'

services:

  mariadb_d:
    image: mariadb
    container_name: mariadb_d
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - mariadb_v:/var/lib/mysql

  adminer_d:
    image: adminer
    ports:
      - 8081:8080
volumes:
  mariadb_v:
