version : '3'
services:
  tomcat_c:
    image: tomcat
    restart: on-failure:3
    ports:
      - 28080:8080
    container_name: apachetomcat
    command:
      - bash
      - -c
      - |
       cd /usr/local/tomcat
       mv webapps webapps-origin
       cp -r webapps.dist/ webapps
       echo  'run tomcat server  ref https://github.com/docker-library/tomcat/blob/master/Dockerfile.template#L286C7-L286C25'
       catalina.sh run
