version : '3'
services:
  mongo_c:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongodb_v:/data/db

  mongo-express_c:
    image: mongo-express
    depends_on:
      - mongo_c
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456 
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo_c:27017/
volumes:
  mongodb_v:

